// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"860","screenHeight":"660","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"walkingand speaking sounds","status":true,"description":"Play specific sounds for each letter typed during dialogue and a sound for every step the player takes.","parameters":{"Step Sound":"Cursor1","Base Typing Volume":"90","Typing Volume Variance":"10","Base Typing Pitch":"100","Typing Pitch Variance":"20","Typing Pan":"0","Step Volume":"90","Step Pitch":"100","Step Pan":"0"}}
];
